### ISSUE TITLE
Download Photos to Device

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Mobile#20]
Client request. Needs to be an optional feature that can be disabled in config if client doesn't want to download the photos or doesn't have space for them. There are still some technical queriesto be bottomed out.

- The existing LibraryLink Web Service can provide either the thumbnails or full-size images for a record, based on the xgKey and xgType provided in the request. The app just needs to connect to the API and request the image
- The LLWS can be configured server-side with whatever criteria are necessary, it willl be configured to return a single image per record at 600x400
- The thumbnails are basically small-size jpeg images.
- The LLWS will provide everything that’s needed for online viewing, for offline viewing we need to save the images to the device.
- On the device, the images can be saved either as image files on the SD card, or in a SQLite database (similar to the map packs). If using a SQLite DB this is likely to have fewer problems in terms of file storage limits (we have seen the Samsung tablets impose a limit on the number of files allowed on the card), but is less likely to be easily pre-seedable (c.f. copying files to a folder on the card).
- To save the thumbnails in a database, they would need converting to BLOB format or a base-64 encoded string.
- The photos would be displayed in the device using the existing photo carousel, but additional config settings would be needed for the LLWS URL.
- To avoid “polluting” the main synchronisation process, the photo synchronisation should be a separate stage (we’ve had enough problems with the sync already) but would need to keep the list of updated records from the main entity sync to use in requesting the photos (i.e. assuming that if a record has changed, we need to get the photo for it, if a record hasn’t changed since the last sync, assume the photo is still valid)
- Stewart previously suggested that a proof of concept to download, save and display an image for a record would take about a week, with a further 1-2 weeks to scale this up to the full dataset.
- Looking at the Pennine Way, they have around 9600 thumbnails which comes to just under 55MB by my estimation. This is probably fairly typical, but unlikely to be the maximum.

**Comment by Timothy-D** [comment]
Minimum Requirement:
- To download a thumbnail of the "primary" photo for a record to the device
- Identification of photo to be downloaded to be defined by LibraryLink Web Service
- Photos to be visible offline

**Comment by Timothy-D** [comment]
Further thoughts:
As this will require the client to purchase the LibraryLink Web service, we need to make sure that CAMS Mobile can operate without trying to download images - this could be handled by a config setting, for example. 
We also need to ensure that this doesn't cause problems for the main synchronisation process - the data sync is fragile enough as it is, and this will potentially involve dragging large volumes of data over the connection. It might be best to completely segregate this from the main data sync, with its own sync button (this could be shown or hidden via the config setting above)

**Comment by LaineS** [comment]
RE: Authentication
I will add an extra config setting in CAMSConfig, this would be the user+pass used by the LLWS service. Then, if required, the LLWS service can be setup with basic auth and use a single user+pass (stored in the client config). NB it will also work in anon mode too.

RE: Test URL
https://camsapidemo.esdm.co.uk/live/mobile/LLWS/librarylinkws.asmx
(this is open with no auth)

**Comment by LaineS** [comment]
Two new config settings added (to CAMSConfig.js)
// CAMS LibraryLink URL
G_SHOW_DOWNLOADBUTTON_FORLIBRARYLINK = true;
G_LIBRARYLINK_GetFileInfoByXGTypeAndXGKey_URL = "https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/LLWS/librarylinkws.asmx/GetFileInfoByXGTypeAndXGKeyWithURLS";


When the button is shown, the app:
1. Shows a button on the data download screen. When you tap it:
- It goes to the LLWS and requests the list of photos for each Furniture, Issue and Maint item
- It makes the max allowed by the browser (6) requests and then goes onto the next request, etc
- It stores all of the metadata in memory and then after it has completed all of the metadata requests it saves these to the DB

2. Then is goes through the list and requests each jpg and downloads to memory. After it downloads all files it then saves these to the DB

3. Each time you tap the download button it will get a full list of images and download them and save to the DB

**Comment by LaineS** [comment]
Testing xgWCP, the Galaxy Tab 2 made 17k requests for metadata (15mins) and completed ok, it saved these to the local DB and then downloaded each of the images 2k (20min)

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.3
**Sync Account**: xgwcp
**Status**: Fail
**Details**: When downloading approx 9,500 photos, the app crashed.

Installed v4.4.3 and downloaded xgwcp config. Synced Routes and LUTs only, then synced photos. This worked OK, and I was able to view photos attached to route records.
Stats: 4161 records with 585 photos.

Synchronised furniture items, then re-synched photos. The app crashed before this completed.
Stats: 13,049 total records with 9,473 photos

No photos are visible in the app, not even the route photos that were previously visible from teh first sync. Going to the photo screen, I see something like this:
![error](https://user-images.githubusercontent.com/25226464/85314209-0f78af80-b4b1-11ea-89f7-e005aa5be112.png)


Key Questions:

1. Where are the photos stored on the device?
2. Are they held as files or in a database?
3. When downloading photos, does it always start from the beginning, or does it know when it has already downloaded a photo?
4. Is it possible to "pre-seed" the photo cache externally from the app?
5. When downloading photos, does it always get every photo, or does it normally do changes only like a regular sync?
6. Is there the option to hold the photos on the removable SD card? might we hit other problems if we are storing everything internally?

**Comment by LaineS** [comment]
Can you change the setting G_LIBRARYLINK_DOWNLOAD_FULLIMAGE = false;

That might help, I managed to download  the whole xgWCP set of images

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.3
**Sync Account**: xgwcp
**Status**: Fail
**Details**:

Deleted data on device, synced issues (4428 records). Tried syncing photos - app crashed. Config was the same as before. 
Exported database, but could not find any sign of photos in there.

Updated configuration to use thumbnails rather than full images. Cleared data and resynchronised. Now able to sync photos without app crashing (of course, image quality is significantly lower).

Photos do not appear against Issue records. I have cross-checked against the desktop CAMS and I know there are valid images against this issue record, but they do not show on the mobile app. An example is Issue 05667on the south-west outskirts of Beaumaris - this has 2 photos in Desktop:
![image](https://user-images.githubusercontent.com/25226464/85430895-a78d9c00-b578-11ea-8346-54a2004876e7.png)
but nothing on Mobile:
![issue](https://user-images.githubusercontent.com/25226464/85431648-ba54a080-b579-11ea-8240-e27aad05a1c0.png)

This seems to be fairly consistent for issues

Furniture items seems more hit-and-miss - some are showing photos but others do not when I know they have photos, eg
Isle/2164 = shows photo
Isle/2165 = shows photo
Isle/2167 = no photo shown but one associated
Isle/2169 = shows photo
Isle/2170 = shows photo
Isle/2171 = shows photo
Isle/2772 = shows photo
Isle/2773 = no photo shown but one associated

These are all around Beaumaris

I'm unable to check whether the images are on the tablet or not.

What is the database file, table and field where the photos are downloaded to?

**Comment by Timothy-D** [comment]
Further testing on this
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.3
**Sync Account**: xgwcp
**Status**: Fail
**Details**: Further testing on this:

1. Connected to the LibraryLink Web service at https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/LLWS/librarylinkws.asmx as used by CAMS Mobile.
2. Invoked method GetFileInfoByXGTypeAndXGKeyWithURLS with xgtype = 'infra', xgkey = 'Isle/2167', MaxNumberOfPhotos = 1. This returned valid data, including the URL for the image: https://camsapidemo.esdm.co.uk/5.1/Reference/XGWCP/LLWS/LLFiles/5398/full_5398.JPG - which is valid.
3. So unclear why this wasn't showing on the tablet.

The LibraryLink web service is returning a single image per record, as constrained by the view, however, teh numbers do not match up, and I am unclear how it is identifying the images it needs to download:

- Deleted all data from the app, synchronised routes only - there are 4164 records
- In the LibraryLink database, there are 585 images associated with routes
- downloaded photos on the tablet: the counter ran from 0 to 12070 - significantly in excess.
- Checked the system log and cross-referenced the URLs with LibraryLink. It had downloaded images that were associated with furniture items, even though there were no furniture items synchronised.

**How and when does the app build the list of photos it needs to download? Does this not get deleted when deleting the rest of the data?**

Looking at the figures in the LibraryLink catalogue database:

Entity | Count
-- | --
Furniture| 9216
Issues| 5975
Route | 585
Total | 15776

Excluding resolved issues, we get

Entity | Count
-- | --
Furniture| 9216
Issues | 4941
Route | 585
total | 14742

Looking at the numbers of records on the tablet, there seems to be a further discrepancy, which suggests that there may be some orphan images in the catalogue:

Entity | Expected Recs | Mobile Recs | Expected Photos | Mobile Photos
--- | --- | --- | --- | ---
Infra | 8888 | 8888 | 8888 |
Maint | 4434 | 4434 | 4434 |
Route | 4164 | 4164 | 585
total | 17486 | 17486 | 13907 | 12070

So not sure what is going on here, and unable to investigate further without access to the photos on the device

**Comment by Timothy-D** [comment]
Further investigation, cross-checking the downloaded records with the LibraryLink database. it seems that some records share a photo, which brings the total number of expected images to **13,327** - I can't account for the missing 1,257

Further testing of full photo download suggests that around 4,000 photos is OK. Attempting to download 8,000 failed – I didn’t see exactly where but think it was between 5,000 & 6,000.

**Comment by Timothy-D** [comment]
Questions that I think we need definitive answers from @LaineS  on:
1.	Where are the photos stored on the device? From Laine’s comments in GitHub I assume this is in _a_ database somewhere, but I couldn't see anything when exporting the Cams Mobile database. What is the path and file name of the database, and which table etc are they stored in?
2.	When downloading photos, it looks like it always wipes everything and starts the whole download process again. Is this correct?
3.	How and when does the app build the list of photos it needs to download? It looks from observation like this does not get deleted when deleting the rest of the data – confirm if this is (a) correct & (b) intentional?
4.	From observation my understanding is that the way the photo download process works is that it gets a list of the photos it needs, and the URLs, then having compiled that list it goes through it downloading images from the URLs. Is this correct? Is there any check whether a file has already been downloaded?

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android 5.1.1
**App Version:** 4.4.3
**Sync Account:** xgWCP
**Synced photos option:** Thumbnails
**Status:** Info

From just an initial basic test having synced Routes and LUTS data only so far, then running the photos sync using the 'thumbnails' config option, I have seen at least a few records showing photos so far (I identified which records to check via the 'xgImageLink' table in the LibraryLink database), so can at least see this is possible for the Samsung Galaxy Tab A device / Android v5.1.1 OS combination. Will test with more data records etc. soon.

Didn't see the exact number of records etc., but it appeared to be:

- 4000-5000 metadata requests: took approx 2 mins
- approx 500-600 photos requests: approx further 30 secs
- so approx. 2 mins 30 secs in total for the Routes photos

With regard to a query @Timothy-D raised regarding the quality of the thumbnail images and whether this is an acceptable compromise if the full size images remains a technical challenge, they do appear ok and still useful when viewed on this device. Obviously it would be nice to have the proper quality image, but this is a good start.

Something I noted from a user interaction perspective is that it would be useful for them to know whether an existing photo exists for them to view, at the point when they are viewing the record's attributes details form, i.e. the existing camera button icon within that record form shows a number decoration when a user takes a new photo, but at the moment for existing synced photos it doesn't show any decoration to show they exist, but if you click that button to take you to the photos carousel, it then shows a decoration number on that duplicate button in the carousel window to reflect the existing synced photo - would be nice to avoid the user having to carry out this extra click to find out whether there is an existing photo for the record.

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android 5.1.1
**App Version:** 4.4.3
**Sync Account:** xgWCP
**Synced photos option:** Thumbnails
**Status:** Info

Upon clearing the synced data using the 'recycle bin' button in the Sync Status window, it appears to only clear the survey data and not the photos, e.g. after clearing the data, then re-running the Routes and LUTs individual syncs, I then went back to a few of the records that had previously had synced photos displayed and they were still displaying them.

Not sure if this is intentional? Maybe would be good to have a separate photos delete recycle bin icon, as when we carry out support for clients the data clear recycle bin button is very useful, but we are likely to not always want to clear the photos during those support processes

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android 5.1.1
**App Version:** 4.4.3
**Sync Account:** xgWCP
**Synced photos option:** Thumbnails
**Status:** Fail

As per @Timothy-D 's comments above, after syncing the Issues data and then re-running the sync photos routine (sync totals and runtime noted below), I can't see any synced photos showing within the Issues records.

Issues photo syncs process:
- 4400 metadata requests: approx 2 mins 30 secs
- 4690 photos requests: approx further 5 mins 30 secs
- so approx. 8 mins in total for the Issues photos (thumbnail format)

**Comment by am-esdm** [comment]
Also, I haven't seem any comments above regarding Land photos? Can't see any reason why this shouldn't be included, so including a note here to remind us to check this and whether they are being synced/are coming through

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android 5.1.1
**App Version:** 4.4.3
**Sync Account:** xgWCP
**Synced photos option:** Thumbnails
**Status:** Fail

Tried syncing photos after just syncing the Land and LUTs data, and it just whirrs round endlessly on the 'Syncing photo data...' message

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android 5.1.1
**App Version:** 4.4.3
**Sync Account:** xgWCP
**Synced photos option:** Full
**Status:** Info

After some investigation yesterday, I was able to identify a useful middle ground between the thumbnail size images and the original size original images, which may help this scenario.

The LibraryLink Web Service (LLWS) offers three image delivery options: original, thumbnail and full. I think in previous conversations around this subject we had only really considered 'thumbnail' and another general full image option, without fully realising there are two full image options (original and full) with different functionality. Currently the 'full' option is in use by CAMS Mobile when requesting the full size images, which is good as that is the more flexible option. When using the 'original' option, the LLWS provides the original image at its original size, however big/massive that may be, likely putting a lot of demand on the sync process and app, particularly for clients with large image catalogues.

When using the 'full' option, the LLWS provides the image optionally resized to a smaller image pixel height/width size as configured in the LLWS' Web.config file under the <add key="imageMaxHeight" value="800"/>
    <add key="imageMaxWidth" value="800"/> config keys. These '800' pixel settings were in place previously on the xgWCP test LLWS, and yesterday afternoon I changed this to 400 (max height and width) and also changed the xgWCP CAMS Mobile config file to request full images rather than thumbnails - note that in order to get refreshed images at the new size, you cannot simply go back to the image url, or even use one of the LLWS method calls (e.g. GetFileURLByID, or GetThumbnailURLByID) to regenerate it, as the LLWS caches the images in its subdirectories on its server and just keeps re-using the existing available images. So if you change these LLWS config entries for 'full' size images, you need to go to the LLWS' 'LLFiles' subdirectory folder, where you'll find folders matching the thumbID of the images, with thumbnail, original and full image files within them (assuming the relevant LLWS calls have been made to generate these for each thumbID), then you'll need to delete all these temporary cached folders and files within the 'LLFiles' directory, then make sure the CAMS Mobile config file is requesting 'full' images, and then re-sync the config on CAMS Mobile (in the current v4.4.3 test version of the app, it would also be wise to reinstall the app to cleanly clear out the existing synced photos), at which point when CAMS Mobile makes the LLWS calls in the sync photos routine, the 'full' image option will pick up the new LLWS imageMaxHeight/imageMaxWidth config settings and use those to generate the appropriately sized images.

The outcome of all of this is that we may be able to find a happy medium ground between the high-resolution large original images (which were placing large demand on the sync and app and causing crashes) and the thumbnail images (which whilst useful are a bit grainy for some purposes). Having set the LLWS configs above to '400' and the CAMS Mobile config to request full images, to start from fresh I reinstalled the v4.4.3 app and synced all the survey data from the xgWCP account, then ran the photos sync, and it ran fully without crashing, which is good. This took:

Metadata sync: approx. 13 mins
Photos sync: approx. further 28 mins
Total: approx 41 mins

Whilst this is a long sync, I think it would be ok within the wider context of it using full images, it representing a full sync from scratch and it being a process that wouldn't necessarily be run too frequently. Ideally we'd like an addition to the functionality to allow change-only syncing of photos as discussed, will detail/discuss the nature of this separately.

Also we can of course tweak the pixel height/width config settings to find the best balance of sync time, image quality and performance. The 400 pixel images look pretty good. It's worth noting that if a higher setting is used, we will of course eventually hit an image size that the tablets wouldn't be able to adequately display the quality of anyway due to screen size, so there is probably a sensible upper limit regarding that to avoid placing redundant extra demand on the sync and app, but with regard to sensible sync times we'd probably use a lower setting anyway. Also there's only so much image detail that Mobile survey use requires anyway.

There is obviously a manual step here to consider for Consultants' work with clients if changing the configured full image size - the LLFiles cached files deletion step, but that's not a huge bother as the configured image size is unlikely to change frequently once decided upon.

There is one more factor in that the LLWS may in some cases be in use by 2 applications, most likely CAMS Mobile and CAMS Web. The LLWS can only have one configured imageMaxHeight/imageMaxWidth config setting, so if both CAMS Mobile and CAMS Web are calling the 'full' image option, they would both have to use the same configured image size. A work around if the client wants to use different 'full' image sizes between the two applications, is to setup a second LLWS instance, which is apparently possible from discussion with CF and RC.

**Comment by am-esdm** [comment]
@Timothy-D : to answer one of the questions above: as described by @LaineS the photos are stored in a table called 'LibraryLink' (not sure on the casing there) in the existing CAMS Mobile database, so probably on the internal device storage

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.3
**Sync Account**: xgwcp
**Status**: Information
**Details**:
Further testing with new LLWS configuration.
- 12086 images downloaded, download completed without error
- Database size = 385MB
- Download completed over 4G connection in less than 1 hour.
- Image quality is good (think these are 400 lines) and I think this setup will be fine for clients. I don't think increasing the resolution would give a valuable improvement.
- Download speed is adequate: this is a large dataset and I think in most cases this will be something that is done at the beginning of the survey season and carried out in the office over wi-fi, so it can be set off and left to run.
- We'll need to make sure we document the required settings on the LLWS.

Further work around this is captured in other issues: #88, #89, #90, #91, #92, #93, #94. I don't think there is anything further to add here.

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android 5.1.1
**App Version:** v4.4.4
**Sync Account:** xgWCP
**Synced photos option:** Full
**Status:** Info

Noticed a problem whereby CAMS Mobile records can end up with an older photo than you are expecting, via a slightly nuanced process:

- Issue record '04669' is a good example, where its latest/highest idThumb is '22703' - you'd therefore expect the image downloaded for this Issue to be the image for that idThumb
- 'vFilterFilesInDatabase' is the view in the LibraryLink database controlling which images are available via the LLWS and the idThumb '22703' is available via that view. The view selects the highest idThumb within each unique xgType and xgKey (record code) combination. From that approach, again you'd expect the image returned for Issue '04669' to be the idThumb '22703' image - which it is at this view stage
- But actually the 'GetFileInfoByXGTypeAndXGKeyWithURLS' LLWS method in use by this CAMS Mobile functionality returns 2 idThumb images for this Issue '04669' (as long as you use the 'requestedMaxNumFiles' parameter with a value of 2 or more). Those are '20537' and '22703', which are both linked to Issue '04669'. The reason both images have been returned though the LLWS (rather than the return being restricted to 1 image as you'd expect from the 'vFilterFilesInDatabase' view), appears to be because the image with the lower idThumb ('20537') is also associated with a Furniture record ('Swans/367' - which also happens to be the parent record of this Issue '04669') and the idThumb '20537' is the latest/highest idThumb for that 'Swans/367' Furniture record, hence it being included in the 'vFilterFilesInDatabase' in association with the Furniture record, when you would otherwise have thought it would be excluded as being the lower idThumb image associated with the Issue record. The 'GetFileInfoByXGTypeAndXGKeyWithURLS' method doesn't recognise which entity type (or record code) the 'vFilterFilesInDatabase' view has provided the idThumb images from, so as long as the idThumbs are available in the view via at least one entity type, this method can return those idThumb values for a different entity type if the idThumb is associated with the requested data record in the wider LibraryLink database (via the xgImageLink table)
- If you use a 'requestedMaxNumFiles' parameter value of 1 in the 'GetFileInfoByXGTypeAndXGKeyWithURLS' LLWS method, it returns a single image with the idThumb '20537' (presumably because they get returned in ascending idThumb order and so this is the first one returned). I'm guessing the CAMS Mobile approach is to use the first image returned, hence this Issue record gets the older idThumb '20537' image downloaded to CAMS Mobile (regardless of whether a 'requestedMaxNumFiles' value of 1, or 2, or higher is used for the request)
- I had a look at the LLWS Web.config file to see if there was any way to configure the LLWS' return to only e.g. return the record with the highest idThumb from the list identified, but I couldn't see an option to do so. So a possible way around this might be to get CAMS Mobile to use a large 'requestedMaxNumFiles' parameter value in its request to allow for as many associated images as possible (the LLWS has a 'absoluteMaxNumFilesToReturn' limit that can be configured - the pre-existing value at the moment is 50 for that in the xgWCP LLWS setup - that should allow for the usual number of images linked with 99.99% of CAMS records (we could even increase that LLWS-configured limit, don't know whether there is a sensible upper limit though)), then select the return with the highest idThumb value, to use to download the image for CAMS Mobile. This would avoid unexpected and old images being downloaded

**Comment by LaineS** [comment]
* Add requestedMaxNumFiles as a config
* Iterate over the returned result and get the highest idThumb URL's

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.5
**Sync Account**: xgWCP
**Status**: Query
**Details**: unusual behaviour when the internet connection is lost partway through the download:
- If signal is lost during the downloadof the metadata:
    - Normally, the metadata counter updates by 50 every 3 seconds or so
    - When signal is lost, the counter updates much faster, going up by 100 in 1 second
    - When signal is restored, the update slows right down, increasing by 50 in 10-15 seconds.
- If signal is lost during download of photos:
    - The counter stops at the current count when signal is lost
    - When signal is restored, it doesn't seem to resume
- The panel on the Sync Status screen does show a number of fialures

**Comment by am-esdm** [comment]
> **Device:** Samsung Galaxy Tab A
> **OS Version:** Android 5.1.1
> **App Version:** v4.4.4
> **Sync Account:** xgWCP
> **Synced photos option:** Full
> **Status:** Info
> 
> Noticed a problem whereby CAMS Mobile records can end up with an older photo than you are expecting, via a slightly nuanced process:
> 
> * Issue record '04669' is a good example, where its latest/highest idThumb is '22703' - you'd therefore expect the image downloaded for this Issue to be the image for that idThumb
> * 'vFilterFilesInDatabase' is the view in the LibraryLink database controlling which images are available via the LLWS and the idThumb '22703' is available via that view. The view selects the highest idThumb within each unique xgType and xgKey (record code) combination. From that approach, again you'd expect the image returned for Issue '04669' to be the idThumb '22703' image - which it is at this view stage
> * But actually the 'GetFileInfoByXGTypeAndXGKeyWithURLS' LLWS method in use by this CAMS Mobile functionality returns 2 idThumb images for this Issue '04669' (as long as you use the 'requestedMaxNumFiles' parameter with a value of 2 or more). Those are '20537' and '22703', which are both linked to Issue '04669'. The reason both images have been returned through the LLWS (rather than the return being restricted to 1 image as you'd expect from the 'vFilterFilesInDatabase' view), appears to be because the image with the lower idThumb ('20537') is also associated with a Furniture record ('Swans/367' - which also happens to be the parent record of this Issue '04669') and the idThumb '20537' is the latest/highest idThumb for that 'Swans/367' Furniture record, hence it being included in the 'vFilterFilesInDatabase' in association with the Furniture record, when you would otherwise have thought it would be excluded as being the lower idThumb image associated with the Issue record. The 'GetFileInfoByXGTypeAndXGKeyWithURLS' method doesn't recognise which entity type (or record code) the 'vFilterFilesInDatabase' view has provided the idThumb images from, so as long as the idThumbs are available in the view via at least one entity type, this method can return those idThumb values for a different entity type if the idThumb is associated with the requested data record in the wider LibraryLink database (via the xgImageLink table)
> * If you use a 'requestedMaxNumFiles' parameter value of 1 in the 'GetFileInfoByXGTypeAndXGKeyWithURLS' LLWS method, it returns a single image with the idThumb '20537' (presumably because they get returned in ascending idThumb order and so this is the first one returned; EDIT: having seen the LLWS return result for a different record (Furniture 'Flint/65') I'm not sure if this order is correct or whether they are shown in 'alphanumeric' order e.g. idThumb '35394' is listed first and '9198' second ('3' then '9')). I'm guessing the CAMS Mobile approach is to use the first image returned, hence this Issue record gets the older idThumb '20537' image downloaded to CAMS Mobile (regardless of whether a 'requestedMaxNumFiles' value of 1, or 2, or higher is used for the request)
> * I had a look at the LLWS Web.config file to see if there was any way to configure the LLWS' return to only e.g. return the record with the highest idThumb from the list identified, but I couldn't see an option to do so. So a possible way around this might be to get CAMS Mobile to use a large 'requestedMaxNumFiles' parameter value in its request to allow for as many associated images as possible (the LLWS has a 'absoluteMaxNumFilesToReturn' limit that can be configured - the pre-existing value at the moment is 50 for that in the xgWCP LLWS setup - that should allow for the usual number of images linked with 99.99% of CAMS records (we could even increase that LLWS-configured limit, don't know whether there is a sensible upper limit though)), then select the return with the highest idThumb value (after casting the values to numeric to order them, if they are ordered alphanumerically), to use to download the image for CAMS Mobile. This would avoid unexpected and old images being downloaded

**Device:** Samsung Galaxy Tab A
**OS Version:** Android v5.1.1
**App Version:** v4.4.5
**Sync Account:** xgWCP
**Status:** Pass - provisional
**Details:**

Tested this same scenario for the Issue record '04669' example above, this version of the app has pulled through the correct image this time - that for idThumb '22703'. No noticeable difference in the time taken to sync the metadata or photos, so the extra idThumb handling for this improvement doesn't appear to have any noticeable performance impact

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.5
**Sync Account**: xgwcp
**Status**: Information/Query
**Details**: Further testing around what happens when signal is lost during a photo download...
- The panel on the Sync Status screen shows a number of failures - so this should indicate to the user that there was a problem 
- In the UI, some records show with the blank image (see below)
- If the signal is lost during the download of the photos, it seems to stall the process and you need to forcibly close and restart the app
- If after the problems you re-sync photos, it seems to fill the holes and resolve the problem.

So how serious is this? There probably isn't much we can do about it as generally the signal loss is caused by external factors, and the user can get around the problem by restarting the app and running the photo download process again when they have signal. It doesn't prevent them surveying with the data they have, so this might be acceptable for this version. Users probably won't be downloading photos that frequently (I see this as something done at the start of the survey season, then maybe each month after that) and should be doing so where they have good signal.

![MissingPhoto](https://user-images.githubusercontent.com/25226464/87688967-8dae3600-c77f-11ea-9230-a852b4d3a71c.png)

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.5
**Sync Account**: xgwcp
**Status**: Information (Pass)
**Details**: Tested with linking other file types (pdf & docx) to records. These were not downloaded to the device, this is correct behaviour as these formats would not display in the app.

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.5
**Sync Account**: xgWCP
**Status**: Information
**Details**: Tested removal of linked files by unlinking through LibraryLink
1. Route Record Isle/1590/1 has 4 linked files:
     a. 9115 = image
     b. 27330 = image
     c. 42627 = image
     d. 42626 = docx
2. Downloaded photos to tablet. Displayed file = 9115
3. Unlinked 9115 via Librarylink
4. Downloaded photos to tablet (without clearing). Displayed file = 42627
5. Unlinked 42627 via LibraryLink
6. Downloaded photos to tablet (without clearing). Displayed file = 42627 - not expected
7. At this point 42627 is NOT among the records returned by the LLWS
8. Deleted all photos
9. Downloaded photos to tablet. No photo shown against this record (LLWS returns 27330 image and 42626 docx)
10. Unlinked 42626 (docx) via LibraryLink.
11. Downloaded phtoso to tablet (without clearing). Displayed file = 27330
12. Unlinked 27330 via LibraryLink. LLWS now returns no records
13. Downloaded photos to tablet (without clearing). Now shows a blank placeholder image (see image in https://github.com/exeGesIS-SDM/CAMS-Mobile/issues/20#issuecomment-663452346)

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.5
**Sync Account**: xgwcp
**Status**: Informational
**Details**: Further testing on non-image file types.
- Link Isle/1580/1
    - file 42646 - docx
    - file 42647 - jpg
- Link Isle/1600/1
    - file 42645 - pdf
- Link Isle/1610/1
    - file 42626 - docx
    - file 9115 - jpg
- Cleared all photos and re-downloaded
    - Link Isle/1580/1 - shows file 42647 (jpg)
    - Link Isle/1600/1 - shows no file
    - Link Isle/1610/1 - shows file 9115 (jpg)

**Comment by Timothy-D** [comment]
**Device**: emulator
**OS Version**: Android 10
**App Version**: 4.4.5
**Sync Account**: xgStaffs
**Status**: Pass
**Details**: Able to download photos, both full size (400) & thumbnails

**Comment by LaineS** [comment]
* Images that have a row in the mobile DB but no metadata are marked up as 'NoMetadata'. Ignore these in the entity photo view (since they appear as a blank page)
* For images that should be shown but for some reason are null in the DB, show an error message on the entity photo screen (currently this is also a blank screen also)

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.6
**Sync Account**: xgWcp
**Status**: Fail (partial)
**Details**: Testing with non-image files:
- Added 3 files to route Isle/0360/1:
    - file 9115 - jpg
    - file 42646 - docx
    - file 42647 - jpg
- Cleared photos from device
- Downloaded photos to device
- Isle/0360/1 shows file 9115 (jpg)
- Unlinked 9115
- Downloaded photos to device
- Isle/0360/1 shows file 42647 (jpg)
- Unlinked 42647
- Downloaded photos to device
- Isle/0360/1 shows file 42647 (jpg) - expected nothing
- Deleted all photos
- Isle/0360/1 shows no image

Would have expected file 42627 to have been removed when it was unlinked.
Also unsure if the order is correct
