### ISSUE TITLE
Unable to sync data with xgEastSus account in v4.4.1

### ISSUE THREAD

**Issue by Timothy-D** [exeGesIS-SDM/CAMS-Mobile#86]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.1
**Status**: NEW ISSUE
**Details**: Since installing 4.4.1 I have been unable to synchronise data with the xgEastSus account. login works fine, but if I try to sync any of the Route, Furniture, Land or Issue dataset, the app crashes with no error message

I was able to synchronise with the same account from the same tablet in v 4.4.0

**Comment by am-esdm** [comment]
**Device:** Samsung Galaxy Tab A
**OS Version:** Android v5.1.1
**App Version:** v4.4.1
**CAMS Mobile sync account:** xgEastSus
**Details:** I got the same result as TD found above using this device and android version. I wonder if this relates to the recent dev work on this issue https://github.com/exeGesIS-SDM/CAMS-Mobile/issues/52 and LS' related comment for that issue: "I think this should be fixed now. A very odd bug, sometimes SQLite was querying the DB and reading any negative numbers as a string. But only doing this sometimes, so it wasn't finding some features...sometimes. Very odd.

I found that by casting the data to a decimal then this behaviour vanished. So, hopefully fixed. I managed to replicate the bug 100% using eastsussex data and it is gone from that test scenario at least."

...Because the whole reason v4.3.12 of the app had to be created was because v4.3.11 had a problem that was only found to affect the East Sussex client so far, whereby the app crashed as soon as they tried to do a full sync (or sync the individual datasets as above (i.e. the map feature ones)). The testing of the v4.3.11 issue by TD and I at the time found that the crash could be caused or avoided by feeding different individual records into the feeding database view, that seemingly had no stand-out differences between them, and it was only when LS opened the dev environment for this that it was possible to see that the crashes were caused by a data handling step within the app that was unable to store the long length of converted (British National Grid to Lat-Long) coordinate values within the associated variables. LS fixed this in v4.3.12 at the time, by changing the datatype of the associated variables. This new bug almost sounds like the reverse (or something similar) may have been applied and could be re-causing that v4.3.11 bug?

**Comment by LaineS** [comment]
Ready to test in v4.4.2

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.2
**Sync Account**: xgEastSus
**Status**: Pass (provisional)
**Details**: Able to connect and sync without error. May need further testing to compare numbers of records, but no errors encountered

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.2
**Sync Account**: xgEastSus
**Status**: Pass (Provisional)
**Details**: Compared record counts in detail - these match OK

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.2
**Sync Account**: xgEastSus
**Status**: Pass (Provisional)
**Details**: Created and updated furniture items and issues on the tablet. these uploaded OK to CAMS Desktop, but I don't have a front end to process them. @am-esdm are you able to process these, please, then I can test the download again?

**Comment by Timothy-D** [comment]
**Device**: Samsung Galaxy Tab Active 2
**OS Version**: Android 9
**App Version**: 4.4.2
**Sync Account**: xgEastSus
**Status**: Pass
**Details**: Data processed and synchronised back down - no errors
