### ISSUE TITLE
v4.4.6: App hangs if your first interaction with Furniture records is to add a new Furniture record

### ISSUE THREAD

**Issue by am-esdm** [exeGesIS-SDM/CAMS-Mobile#99]
v4.4.6 app hangs on the 'Creating record...' message window if your first interaction with Furniture records is to add a new Furniture record. If you first open an existing Furniture record (i.e. open the record form) before adding any new Furniture record, you don't appear to get the problem for the rest of your session working on CAMS Mobile, i.e. you can then add new Furniture records ok. The problem only then re-occurs when you re-start CAMS Mobile, where the same workaround applies again

**Comment by LaineS** [comment]
**Fixed in v4.4.7**
- When cresating a new furniture record for the first time the form was opening and failing when trying to set the badge number to 0. This is now fixed

No other code changes where made in the release. Tested this issue on the emulator only (API 29), but I'm not expecting any other problems.

**Comment by am-esdm** [comment]
Thanks Laine. For reference if any of us look back at this: it's the camera button badge number we're talking about here

**Comment by am-esdm** [comment]
Have now carried out a range of testing with v4.4.7 (test sync account xgWCP, tab A device, Android v5.1.1) - TD has also done some testing with other sync accounts, this looks fine now
